"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version = 2
final_space = false
shell_integration = true
console_title_template = "{{ .Shell }} in {{ .PWD }}"

[palette]
rosewater = "#F5E0DC"
flamingo = "#F2CDCD"
pink = "#F5C2E7"
mauve = "#CBA6F7"
red = "#F38BA8"
maroon = "#EBA0AC"
peach = "#FAB387"
yellow = "#F9E2AF"
green = "#A6E3A1"
teal = "#94E2D5"
sky = "#89DCEB"
sapphire = "#74C7EC"
blue = "#89B4FA"
lavender = "#B4BEFE"
text = "#CDD6F4"
subtext1 = "#BAC2DE"
subtext0 = "#A6ADC8"
overlay2 = "#9399B2"
overlay1 = "#7F849C"
overlay0 = "#6C7086"
surface2 = "#585B70"
surface1 = "#45475A"
surface0 = "#313244"
base = "#1E1E2E"
mantle = "#181825"
crust = "#11111B"
true = "p:green"
false = "p:red"
time = "p:overlay1"
os-fg = "p:base"
os-bg = "p:overlay1"
root-fg = "p:base"
root-bg = "p:yellow"
path = "p:yellow"
git = "p:lavender"
docker = "p:sky"
go = "p:mauve"
haskell = "p:mauve"
julia = "p:mauve"
lua = "p:mauve"
python = "p:mauve"
rust = "p:mauve"

[transient_prompt]
foreground = "p:time"
template = '{{ now | date "15:04:05" }} {{ if gt .Code 0 }}<p:false>❯</>{{ else }}<p:true>❯</>{{ end }} '

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

  [[blocks.segments]]
  type = "path"
  style = "plain"
  foreground = "p:path"
  template = " {{ .Path }} "

    [blocks.segments.properties]
    home_icon = "~"
    folder_icon = ".."
    style = "agnoster_short"

  [[blocks.segments]]
  type = "git"
  style = "plain"
  foreground = "p:git"
  template = "{{ .HEAD }} "

    [blocks.segments.properties]
    branch_icon = " "
    cherry_pick_icon = " "
    commit_icon = " "
    fetch_status = false
    fetch_stash_count = false
    fetch_upstream_icon = false
    merge_icon = " "
    no_commits_icon = " "
    rebase_icon = " "
    revert_icon = " "
    tag_icon = " "

  [[blocks.segments]]
  type = "docker"
  style = "plain"
  foreground = "p:docker"
  template = " {{ .Context }} "

  [[blocks.segments]]
  type = "go"
  style = "plain"
  foreground = "p:go"
  template = " {{ if not .Error }}{{ .Full }}{{ end }} "

  [[blocks.segments]]
  type = "haskell"
  style = "plain"
  foreground = "p:haskell"
  template = " {{ if not .Error }}{{ .Full }}{{ end }} "

  [[blocks.segments]]
  type = "julia"
  style = "plain"
  foreground = "p:julia"
  template = " {{ if not .Error }}{{ .Full }}{{ end }} "

  [[blocks.segments]]
  type = "lua"
  style = "plain"
  foreground = "p:lua"
  template = " {{ if not .Error }}{{ .Full }}{{ end }} "

  [[blocks.segments]]
  type = "python"
  style = "plain"
  foreground = "p:python"
  template = " {{ if not .Error }}{{ if .Venv }}venv/{{ end }}{{ .Full }}{{ end }} "

    [blocks.segments.properties]
    display_default = false
    display_mode = "context"

  [[blocks.segments]]
  type = "rust"
  style = "plain"
  foreground = "p:rust"
  template = " {{ if not .Error }}{{ .Full }}{{ end }} "

  [[blocks.segments]]
  type = "executiontime"
  style = "plain"
  foreground = "p:true"
  foreground_templates = [ "{{ if .Code }}p:false{{ end }}" ]
  template = "󰔟 {{ .FormattedMs }} "

    [blocks.segments.properties]
    threshold = 500
    #style = "austin"

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

  [[blocks.segments]]
  type = "status"
  style = "plain"
  foreground = "p:true"
  foreground_templates = [ "{{ if gt .Code 0 }}p:false{{ end }}" ]
  template = "❯ "

    [blocks.segments.properties]
    always_enabled = true

